// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortCodeGeneratorService.Data;

#nullable disable

namespace ShortCodeGeneratorService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250710052252_Initialcreate")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ShortCodeGeneratorService.Models.ShortCode", b =>
                {
                    b.Property<int>("ShortCodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShortCodeID"));

                    b.Property<string>("ShortCodeCreatedAt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortCodeDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortCodeURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShortCodeID");

                    b.ToTable("ShortCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
